#25 RubyKaigiオンライン参加レポート記事追加
h2carrot/h2carrot.github.io pull request #35
Opened 2023-05-13 15:48 UTC by kcscarrot-hataoka

RubyKaigi2023オンライン参加のセッションレポート記事追加しました。
レビューお願いします。

2023-05-15 03:28 UTC, kcscarrot-ooki requested changes

2023-05-18 02:18 UTC, emorima requested changes

2023-05-18 02:18 UTC, emorima commented on _posts/2023-05-14-rubykaigi2023-session-reports-at-online.md
> +permalink: /2023/05/14-rubykaigi2023-session-reports-at-online
saitoくん、hasumi さんのレポートの permalink を 以下のようにしてもらったので、末尾に 03つけて欲しいです!
- rubykaigi2023-session-reports-at-online01
- rubykaigi2023-session-reports-at-online02

2023-05-18 02:22 UTC, kcscarrot-hataoka commented on _posts/2023-05-14-rubykaigi2023-session-reports-at-online.md
> +permalink: /2023/05/14-rubykaigi2023-session-reports-at-online
@emorima 
記事の日付的に私の記事の方が先に来てしまいますが、日付も2人に合わせた方が良いですか？

2023-05-18 02:25 UTC, kcscarrot-shinomiya commented on _posts/2023-05-14-rubykaigi2023-session-reports-at-online.md
> +その中でもいくつか印象に残ったものをいくつかピックアップさせていただきます。
`いくつか`が繰り返されてて違和感あったので、↓の方が良さそうかなと思います。
```suggestion
その中でも印象に残ったものをいくつかピックアップさせていただきます。  
```

2023-05-18 02:37 UTC, kcscarrot-kodaira commented on _posts/2023-05-14-rubykaigi2023-session-reports-at-online.md
> +例えば、Alpha Releaseをした時、それまでは1人で開発していたけれど自分以外の人たちの意見を聞くようになり、自分だけでは気付かないこと学んだという話をされていました。
「気付かないこと学んだ」に「を」が必要かと思います。
→ 「気付かないことを学んだ」

2023-05-18 02:37 UTC, emorima commented on _posts/2023-05-14-rubykaigi2023-session-reports-at-online.md
> +permalink: /2023/05/14-rubykaigi2023-session-reports-at-online
@kcscarrot-hataoka あ、確かに~
日付前だから先に表示されるのに、03 は違和感あるので、日付も合わせてください！

2023-05-18 03:24 UTC, kcscarrot-hataoka commented on _posts/2023-05-14-rubykaigi2023-session-reports-at-online.md
> +permalink: /2023/05/14-rubykaigi2023-session-reports-at-online
修正しました。ご確認お願いします。

2023-05-18 03:24 UTC, kcscarrot-hataoka commented on _posts/2023-05-14-rubykaigi2023-session-reports-at-online.md
> +その中でもいくつか印象に残ったものをいくつかピックアップさせていただきます。
修正しました。

2023-05-18 03:24 UTC, kcscarrot-hataoka commented on _posts/2023-05-14-rubykaigi2023-session-reports-at-online.md
> +例えば、Alpha Releaseをした時、それまでは1人で開発していたけれど自分以外の人たちの意見を聞くようになり、自分だけでは気付かないこと学んだという話をされていました。
修正しました。

2023-05-18 03:51 UTC, kcscarrot-kodaira commented on _posts/2023-05-17-rubykaigi2023-session-reports-at-online03.md
> +また、最初のPublic Releaseした時は、メーリングリストで最初に「リリースおめでとうございます」というメールが来たけれど、次のメールで「でも私の環境では動きません」というメールが来たなんて話をされて、直接こういう風に開発者とコミュニケーションを取れる環境があることの良さを話されていました。
「Public Releaseした時」こちらも「Public Releaseをした時」の方が良いかなと思います！
一行上で、「Alpha Releaseをした時」としているので！
※五月雨式でごめんなさい。

2023-05-18 04:33 UTC, kcscarrot-hataoka commented on _posts/2023-05-17-rubykaigi2023-session-reports-at-online03.md
> +また、最初のPublic Releaseした時は、メーリングリストで最初に「リリースおめでとうございます」というメールが来たけれど、次のメールで「でも私の環境では動きません」というメールが来たなんて話をされて、直接こういう風に開発者とコミュニケーションを取れる環境があることの良さを話されていました。
修正しました。

2023-05-18 05:14 UTC, kcscarrot-kodaira approved these changes

2023-05-18 07:36 UTC, emorima approved these changes

2023-05-18 07:50 UTC, kcscarrot-ooki approved these changes

2023-05-19 02:26 UTC, merged