#23 KeebKaigi参加レポート記事作成
h2carrot/h2carrot.github.io pull request #43
Opened 2023-06-05 12:51 UTC by kcscarrot-ooki

2023-06-06 06:25 UTC, emorima requested changes
⌨️ タグを増やしていきたいので、Keyboard タグ追加しましょう～！

2023-06-06 06:25 UTC, emorima commented on _posts/2023-06-06-keebkaigi2023-reports.md
> +tags: [Ruby]
```suggestion
tags: [Ruby, Keyboard]
```

⌨️ 入れていこう

2023-06-06 09:43 UTC, kcscarrot-ooki commented on _posts/2023-06-06-keebkaigi2023-reports.md
> +tags: [Ruby]
追加しました

2023-06-07 22:20 UTC, emorima reviewed
typo の件は、suggestでシュッとcommitできるようにしておきました！

2023-06-07 22:20 UTC, emorima commented on _posts/2023-06-06-keebkaigi2023-reports.md
> +@takkanm さんの発表は、自作キーボードに関するコミュニティや、Youbube チャンネルなどを紹介する、
```suggestion
@takkanm さんの発表は、自作キーボードに関するコミュニティや、Youtube チャンネルなどを紹介する、
```

suggest機能を使うのだ～

2023-06-07 22:20 UTC, emorima commented on _posts/2023-06-06-keebkaigi2023-reports.md
> +実際にはたくさんの応募があり、泣く泣く搾っての11名とのことです。
```suggestion
実際にはたくさんの応募があり、泣く泣く絞っての11名とのことです。  
```

2023-06-08 11:59 UTC, kcscarrot-ooki commented on _posts/2023-06-06-keebkaigi2023-reports.md
> +---
```suggestion
img: /assets/images/keebkaigi2023/keebkaigi2023_tenji_space1.jpg
---
```

2023-06-08 12:00 UTC, emorima approved these changes

2023-06-08 12:00 UTC, emorima approved these changes

2023-06-08 12:00 UTC, emorima approved these changes

2023-06-08 12:03 UTC, merged