AWS 勉強会向け準備記事の追加
h2carrot/h2carrot.github.io pull request #50
Opened 2024-06-25 08:48 UTC by Naoya-Kishinami

## 目的

2023年度に実施していた AWS 勉強会の準備部分を記事にしました。

## 動作確認

VSCode のプレビューでは、イメージ通りに表示されることは確認済。

## 特にレビューして欲しい点

- 不足している事項などがありましたら、ご指摘下さい。
- AWS アカウント ID など、秘匿箇所は記載していない筈ですが、見落としがありましたらご指摘下さい。

2024-06-28 03:28 UTC, kcscarrot-hataoka commented on _posts/2024-06-23-aws-study2023-0.md
> +author: kishinami
ここ、GitHubのプロフィールへのリンクで使用しているので、GitHubのアカウント名にしてほしいです

2024-07-02 02:56 UTC, Naoya-Kishinami commented on _posts/2024-06-23-aws-study2023-0.md
> +author: kishinami
すみません、確認が遅れました。 :bow:

author を GitHub Account 名に変更させて頂きましたので、ご確認をお願いいたします。

2024-07-02 06:07 UTC, kcscarrot-hataoka approved these changes

2024-07-03 08:31 UTC, kcscarrot-ooki requested changes

2024-07-03 08:31 UTC, kcscarrot-ooki commented on _posts/2024-06-23-aws-study2023-0.md
> +permalink: /2023/06/23-aws-study2023-0
published_at と合わせて /2024/06/23-aws-study2023-0 が良いと思います～

2024-07-03 11:30 UTC, Naoya-Kishinami commented on _posts/2024-06-23-aws-study2023-0.md
> +permalink: /2023/06/23-aws-study2023-0
ご指摘ありがとうございます！、修正させて頂きましたので、ご確認をお願いいたします。 :bow:

2024-07-03 23:57 UTC, aoirolamp approved these changes
修正確認しました！

2024-07-04 00:18 UTC, aoirolamp approved these changes

2024-07-04 00:18 UTC, aoirolamp commented on _posts/2024-06-23-aws-study2023-0.md
> +permalink: /2023/06/23-aws-study2023-0
確認しました

2024-07-04 00:21 UTC, kcscarrot-ooki approved these changes

2024-07-04 00:21 UTC, kcscarrot-ooki commented on _posts/2024-06-23-aws-study2023-0.md
> +permalink: /2023/06/23-aws-study2023-0
確認しました

2024-07-04 00:22 UTC, kcscarrot-ooki approved these changes

2024-07-04 00:29 UTC, kcscarrot-shinomiya approved these changes

2024-07-04 00:29 UTC, merged