[記事作成] RubyKaigi2024座談会
h2carrot/h2carrot.github.io pull request #58
Opened 2024-07-23 11:42 UTC by kcscarrot-ooki

RubyKaigi 2024参加レポート改め、座談会の記事です。

2024-07-24 01:00 UTC, emorima requested changes

2024-07-24 01:00 UTC, emorima commented on _posts/2024-07-19-rubykaigi2024.md
> +* 大木： 確かにそうですね。やっぱり Ruby Kaigi とかに参加すると漠然と何か触れてみたいっていう思いが強くなりますよね。
@kcscarrot-ooki "RubyKaigi" が正しい名称です～

2024-07-24 01:28 UTC, kcscarrot-kudo commented on _posts/2024-07-19-rubykaigi2024.md
> +* 工藤： 今、フォロワー今野さんしかいないですからね。
```suggestion
* 工藤： 今、フォロワー今野さんしかいないですからね。
   *  [@kupasse_doppied](https://x.com/kupasse_doppied) ← 工藤のアカウントです。よかったら...。
```

2024-07-24 05:16 UTC, kcscarrot-konno commented on _posts/2024-07-19-rubykaigi2024.md
> +* 今野： 最終日の正規表現エンジンをRubyで実装する！みたいなトークがあったじゃないですか。そのトークが面白くて凄く引き込まれて。
読み合わせのときに気付かず申し訳ないです……
ここだけ実際のセッションへのリンクが無かったので追加をお願いしたいです :pray:

```suggestion
* 今野： 最終日にあった、正規表現エンジンをRubyで自作するセッション [Make Your Own Regex Engine!](https://rubykaigi.org/2024/presentations/makenowjust.html#day3) が面白くて凄く引き込まれて。
```

2024-07-24 08:52 UTC, kcscarrot-ooki commented on _posts/2024-07-19-rubykaigi2024.md
> +* 大木： 確かにそうですね。やっぱり Ruby Kaigi とかに参加すると漠然と何か触れてみたいっていう思いが強くなりますよね。
修正しました～

2024-07-25 09:52 UTC, kcscarrot-shinomiya approved these changes

2024-07-26 11:51 UTC, kcscarrot-hataoka commented on _posts/2024-07-19-rubykaigi2024.md
> +* 工藤： 楽しそう！
rich diff の方で見ると、この辺り崩れて見えるんですが、rich diff で見た時だけですかね…？

2024-07-29 00:22 UTC, kcscarrot-ooki commented on _posts/2024-07-19-rubykaigi2024.md
> +* 工藤： 楽しそう！
@kcscarrot-hataoka 
確かに rich diff では崩れてますね。  
手元で jekyll server 起動して表示させると問題なさそうではあります。  
![image](https://github.com/user-attachments/assets/6fe79033-dc31-4341-bda1-4a980f872bf6)

2024-07-29 00:22 UTC, kcscarrot-ooki commented on _posts/2024-07-19-rubykaigi2024.md
> +* 大木： 確かにそうですね。やっぱり Ruby Kaigi とかに参加すると漠然と何か触れてみたいっていう思いが強くなりますよね。
@emorima ↑ 確認お願いします！

2024-07-29 00:41 UTC, kcscarrot-hataoka commented on _posts/2024-07-19-rubykaigi2024.md
> +* 工藤： 楽しそう！
rich diffだけなら問題なさそうですね

2024-07-29 00:42 UTC, kcscarrot-hataoka approved these changes

2024-07-29 00:59 UTC, emorima commented on _posts/2024-07-19-rubykaigi2024.md
> +* 大木： 確かにそうですね。やっぱり Ruby Kaigi とかに参加すると漠然と何か触れてみたいっていう思いが強くなりますよね。
OK!

2024-07-29 01:00 UTC, emorima approved these changes

2024-07-29 01:00 UTC, emorima commented
@kcscarrot-ooki approveしました

2024-08-01 01:07 UTC, merged