[記事作成] 社内読書会
h2carrot/h2carrot.github.io pull request #73
Opened 2024-10-10 09:29 UTC by kcscarrot-ooki

記事の追加になります。  
レビューお願いします。

2024-10-16 01:43 UTC, kcscarrot-shinomiya approved these changes

2024-12-05 12:25 UTC, kcscarrot-hataoka commented on _posts/2024-10-07-rindokukai.md
> +* 参するにあたって事前準備等の負担が少なく、続けやすい
(レビュー遅くなって本当に申し訳ない…)

ここって「参加する」のtypo…？

2024-12-06 06:10 UTC, kcscarrot-konno requested changes

2024-12-06 06:10 UTC, kcscarrot-konno commented on _posts/2024-10-07-rindokukai.md
> +今までに2冊読み終え、現在は[エンジニアリングマネージャーの仕事](https://www.oreilly.co.jp/books/9784873119946/)
```suggestion
今までに2冊読み終え、現在は[エンジニアリングマネージャーのしごと](https://www.oreilly.co.jp/books/9784873119946/)
```

細かくてすみません… 固有名詞なのでここは直した方が良さそうだと思いました。

2024-12-20 00:13 UTC, kcscarrot-ooki commented on _posts/2024-10-07-rindokukai.md
> +* 参するにあたって事前準備等の負担が少なく、続けやすい
typoです
修正しました

2024-12-20 00:55 UTC, kcscarrot-hataoka approved these changes

2024-12-20 01:09 UTC, kcscarrot-konno approved these changes

2025-01-09 11:08 UTC, merged